import type { SceneDef } from '../types';

export const SCENES: SceneDef[] = [
  {
    id: 'forest',
    name: '森林',
    nameEn: 'Forest',
    icon: '🌲',
    description: '清晨林间，鸟鸣与风声交织',
    gradient: 'from-emerald-950 via-green-900 to-teal-950',
    layers: [
      { 
        id: 'forest_wind', 
        name: '林间风声', 
        type: 'base', 
        defaultVolume: 0.6,
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.3,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.3,
          volumeAxis: 'x',
        },
      },
      { 
        id: 'forest_leaves', 
        name: '树叶沙沙', 
        type: 'base', 
        defaultVolume: 0.4,
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.5,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
      {
        id: 'forest_bird1',
        name: '远处鸟鸣',
        type: 'detail',
        defaultVolume: 0.55,
        triggerInterval: { min: 4000, max: 12000 },
        spatialBehavior: {
          panAffected: true,
          basePan: -0.3,
          panRange: 0.6,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.5,
          volumeAxis: 'x',
        },
      },
      {
        id: 'forest_bird2',
        name: '近处鸟啼',
        type: 'detail',
        defaultVolume: 0.45,
        triggerInterval: { min: 8000, max: 20000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0.3,
          panRange: 0.8,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.7,
          volumeAxis: 'x',
        },
      },
      {
        id: 'forest_stream',
        name: '溪流涓涓',
        type: 'base',
        defaultVolume: 0.3,
        spatialBehavior: {
          panAffected: true,
          basePan: -0.5,
          panRange: 0.4,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.4,
          volumeAxis: 'x',
        },
      },
    ],
    timeOfDay: ['morning', 'afternoon'],
    weather: ['sunny', 'cloudy'],
    moods: ['calm', 'focus', 'refreshed'],
  },
  {
    id: 'cafe',
    name: '咖啡厅',
    nameEn: 'Café',
    icon: '☕',
    description: '温馨小店，轻语与咖啡香气',
    gradient: 'from-amber-950 via-orange-900 to-stone-950',
    layers: [
      { 
        id: 'cafe_chatter', 
        name: '轻声交谈', 
        type: 'base', 
        defaultVolume: 0.5,
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.4,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
      { 
        id: 'cafe_music', 
        name: '背景音乐', 
        type: 'base', 
        defaultVolume: 0.25,
        spatialBehavior: {
          panAffected: false,
          basePan: 0,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
      {
        id: 'cafe_machine',
        name: '咖啡机',
        type: 'detail',
        defaultVolume: 0.5,
        triggerInterval: { min: 10000, max: 25000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0.6,
          panRange: 0.3,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.4,
          volumeAxis: 'x',
        },
      },
      {
        id: 'cafe_clink',
        name: '杯碟碰撞',
        type: 'detail',
        defaultVolume: 0.45,
        triggerInterval: { min: 5000, max: 15000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.7,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.3,
          volumeAxis: 'x',
        },
        triggerRelations: [
          {
            targetLayerId: 'cafe_machine',
            probabilityMultiplier: 2,
            durationMs: 5000,
          },
        ],
      },
      {
        id: 'cafe_door',
        name: '门铃叮咚',
        type: 'detail',
        defaultVolume: 0.4,
        triggerInterval: { min: 20000, max: 45000 },
        spatialBehavior: {
          panAffected: true,
          basePan: -0.7,
          panRange: 0.2,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
    ],
    timeOfDay: ['morning', 'afternoon', 'evening'],
    weather: ['sunny', 'cloudy', 'rainy'],
    moods: ['social', 'focus', 'energized'],
  },
  {
    id: 'rain',
    name: '雨天',
    nameEn: 'Rainy Day',
    icon: '🌧️',
    description: '窗外细雨，偶有远雷低鸣',
    gradient: 'from-slate-950 via-blue-950 to-indigo-950',
    layers: [
      { 
        id: 'rain_heavy', 
        name: '雨声', 
        type: 'base', 
        defaultVolume: 0.65,
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.3,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
      { 
        id: 'rain_window', 
        name: '窗上雨滴', 
        type: 'base', 
        defaultVolume: 0.35,
        spatialBehavior: {
          panAffected: true,
          basePan: 0.2,
          panRange: 0.5,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.4,
          volumeAxis: 'x',
        },
      },
      {
        id: 'rain_thunder',
        name: '远处雷声',
        type: 'detail',
        defaultVolume: 0.45,
        triggerInterval: { min: 15000, max: 40000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.8,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.6,
          volumeAxis: 'x',
        },
      },
      {
        id: 'rain_drip',
        name: '屋檐水滴',
        type: 'detail',
        defaultVolume: 0.4,
        triggerInterval: { min: 2000, max: 6000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0.4,
          panRange: 0.4,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.3,
          volumeAxis: 'x',
        },
      },
    ],
    timeOfDay: ['morning', 'afternoon', 'evening', 'night'],
    weather: ['rainy', 'stormy'],
    moods: ['calm', 'sleepy', 'melancholy'],
  },
  {
    id: 'study',
    name: '深夜书房',
    nameEn: 'Night Study',
    icon: '🕯️',
    description: '万籁俱寂，唯有书页与钟摆',
    gradient: 'from-stone-950 via-zinc-900 to-neutral-950',
    layers: [
      { 
        id: 'study_room', 
        name: '室内静谧', 
        type: 'base', 
        defaultVolume: 0.3,
        spatialBehavior: {
          panAffected: false,
          basePan: 0,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
      {
        id: 'study_clock',
        name: '时钟滴答',
        type: 'detail',
        defaultVolume: 0.35,
        triggerInterval: { min: 1000, max: 1000 },
        spatialBehavior: {
          panAffected: true,
          basePan: -0.3,
          panRange: 0.2,
          volumeAffected: false,
          volumeAxis: 'x',
        },
      },
      {
        id: 'study_page',
        name: '翻书声',
        type: 'detail',
        defaultVolume: 0.4,
        triggerInterval: { min: 8000, max: 20000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0,
          panRange: 0.6,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.4,
          volumeAxis: 'x',
        },
        triggerRelations: [
          {
            targetLayerId: 'study_pen',
            probabilityMultiplier: 3,
            durationMs: 3000,
          },
        ],
      },
      {
        id: 'study_pen',
        name: '书写声',
        type: 'detail',
        defaultVolume: 0.35,
        triggerInterval: { min: 5000, max: 15000 },
        spatialBehavior: {
          panAffected: true,
          basePan: 0.2,
          panRange: 0.5,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.3,
          volumeAxis: 'x',
        },
      },
      {
        id: 'study_owl',
        name: '远处猫头鹰',
        type: 'detail',
        defaultVolume: 0.3,
        triggerInterval: { min: 30000, max: 60000 },
        spatialBehavior: {
          panAffected: true,
          basePan: -0.5,
          panRange: 0.6,
          volumeAffected: true,
          baseVolumeMultiplier: 1,
          volumeRangeMultiplier: 0.5,
          volumeAxis: 'x',
        },
      },
    ],
    timeOfDay: ['evening', 'night'],
    weather: ['any'],
    moods: ['focus', 'calm', 'sleepy'],
  },
];
